spring.application.name=springboot-integration
channel.input=request-emp-name-channel
channel.hire.employee=request-hire-emp-channel

channel.employee.status=emp-status-channel

channel.employee.managers=emp-managers-channel

channel.employee.designation=dev-emp-channel